version: '3'
services:
  digimart:
    build:
      context: .
      dockerfile: Dockerfile_app
    expose:
      - "3000"
    links:
      - mysql:db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - digimart:app

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: digimart
    volumes:
      - ./infrastructure/:/docker-entrypoint-initdb.d
    expose:
      - "3306"